### ISSUE TITLE
FIle Not Found in Database

### ISSUE THREAD

**Issue by zacrag** [stevezau/plex_generate_vid_previews#17]
It seems as though my install is working correctly, but finds an issue with the files in the database folder. Terminal output below:

2023-05-29 18:29:32.072 | INFO     | __main__:run:221 - Getting Movies from Plex

2023-05-29 18:29:36.855 | INFO     | __main__:run:223 - Got 3535 Movies from Plex
⠋ Working...                                            0% -:--:--    0/3535
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/process.py", line 256, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ragslinux/Downloads/plex_generate_previews.py", line 196, in process_item
    os.mkdir(indexes_path)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/PlexDB/mnt/plexdatabase/Database/Library/Application Support/Plex Media Server/Media/1/1acb721be80391c103803a043e573d02ea73c03.bundle/Contents/Indexes'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ragslinux/Downloads/plex_generate_previews.py", line 269, in <module>
    run()
  File "/home/ragslinux/Downloads/plex_generate_previews.py", line 231, in run
    future.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/PlexDB/mnt/plexdatabase/Database/Library/Application Support/Plex Media Server/Media/1/1acb721be80391c103803a043e573d02ea73c03.bundle/Contents/Indexes'

**Comment by stevezau** [comment]
It is saying no such file or directory. Does /mnt/PlexDB/mnt/plexdatabase/Database/Library/Application Support/Plex Media Server/Media/1/1acb721be80391c103803a043e573d02ea73c03.bundle/Contents/Indexes exist?

**Comment by stevezau** [comment]
Closing due to no reply.
