### ISSUE TITLE
[Errno 2] No such file or directory 

### ISSUE THREAD

**Issue by deepfriedbutter** [stevezau/plex_generate_vid_previews#30]
Getting this error when trying to run the script. 

``concurrent.futures.process._RemoteTraceback:`
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/administrator/./plex_generate_previews.py", line 212, in process_item
    os.mkdir(indexes_path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Media/9/50aba4dd1dc622d128431d7f21feca8c2b31cfa.bundle/Contents/Indexes'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/administrator/./plex_generate_previews.py", line 285, in <module>
    run()
  File "/home/administrator/./plex_generate_previews.py", line 247, in run
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/plexmediaserver/Library/Application Support/Plex Media `Server/Media/9/50aba4dd1dc622d128431d7f21feca8c2b31cfa.bundle/Contents/Indexes'`

**Comment by stevezau** [comment]
What t-shooting have you done? Are your paths correct and accessible by the script? It seems that an error is suggested now.

**Comment by deepfriedbutter** [comment]
sorry, i fixed it. I had a "localhost" folder under the "Media" folder and that's where the data was. Please close!

**Comment by deepfriedbutter** [comment]
closing
